<a href="https://colab.research.google.com/github/ambikaa99/Python_ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array(23)
print(a)

23


In [ ]:
b=np.array([1,2,3,])
print(b)

[1 2 3]


In [ ]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a)
print(b[0])
print

23
1
